version: '3'

services:
  titiler:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - CPL_TMPDIR=/tmp
      - GDAL_CACHEMAX=75%
      - GDAL_DISABLE_READDIR_ON_OPEN=EMPTY_DIR
      - GDAL_HTTP_MERGE_CONSECUTIVE_RANGES=YES
      - GDAL_HTTP_MULTIPLEX=YES
      - GDAL_HTTP_VERSION=2
      - PORT=3000
      - PYTHONWARNINGS=ignore
      - VSI_CACHE=TRUE
      - VSI_CACHE_SIZE=536870912
      - WORKERS_PER_CORE=1
      # - TITILER_API_DISABLE_STAC=TRUE
      # - TITILER_API_DISABLE_MOSAIC=TRUE
      # - TITILER_API_DISABLE_COG=TRUE

  redis:
    image: redis:6.2-rc-alpine
    ports: ["6379:6379"]
    container_name: titiler-redis
    entrypoint: >
      /bin/sh -c "
        echo '
        maxmemory 1gb
        maxmemory-policy allkeys-lru
        appendonly no
        save \"\"
        dir /tmp
        ' |
        redis-server -
      "
    volumes:
      - ".data/redis:/data"
