version: 2.1

orbs:
  k8s-build-deploy: saildrone/k8s-build-deploy@0.2

docker_config: &docker_config
  base_image: ${SD_BASE_PYTHON_3_8}

branch_config: &branch_config
  production_branch: &production_branch prod
  staging_branch: &staging_branch main
  development_branch: &development_branch dev

context: &context platform-k8s

filter_config: &filter_config
  filters:
    branches:
      only:
        - *production_branch
        - *staging_branch
        - *development_branch

workflows:
  build_and_test:
    jobs:
      - k8s-build-deploy/build-lint-manifest:
          <<: *branch_config
          context: *context
          <<: *filter_config

      - k8s-build-deploy/build-push-image:
          docker_layer_caching_enabled: false
          <<: *docker_config
          <<: *branch_config
          context: *context
          <<: *filter_config

      - k8s-build-deploy/deploy-k8s-manifests:
          <<: *branch_config
          context: *context
          requires:
            - k8s-build-deploy/build-push-image
            - k8s-build-deploy/build-lint-manifest
          <<: *filter_config
