version: 2.1

orbs:
  k8s-build-deploy: saildrone/k8s-build-deploy@0.1

fingerprint: &fingerprint
  "13:a6:81:74:d7:d6:6a:32:47:32:aa:f5:f0:48:3f:64"

docker_config: &docker_config
  base_image: ${SD_BASE_PYTHON_3_8}

branch_config: &branch_config
  production_branch: &production_branch prod
  #staging_branch: &staging_branch sd-master
  staging_branch: &staging_branch df/nrt-file-list
  development_branch: &development_branch dev

context: &context platform-k8s

filter_config: &filter_config
  filters:
    branches:
      only:
        - *production_branch
        - *staging_branch
        - *development_branch

workflows:
  build_and_test:
    jobs:
      - k8s-build-deploy/build-lint-manifest:
          circleci_ssh_fingerprint: *fingerprint
          prerun_args: "-v 2.6.2"
          <<: *branch_config
          context: *context
          <<: *filter_config

      - k8s-build-deploy/build-push-image:
          circleci_ssh_fingerprint: *fingerprint
          docker_layer_caching_enabled: false
          <<: *docker_config
          <<: *branch_config
          context: *context
          <<: *filter_config

      - k8s-build-deploy/deploy-k8s-manifests:
          circleci_ssh_fingerprint: *fingerprint
          <<: *branch_config
          context: *context
          requires:
            - k8s-build-deploy/build-push-image
            - k8s-build-deploy/build-lint-manifest
          <<: *filter_config
